import os
import argparse
from data_store import DataStore
from job_manager import JobManager
from llm_agent import LLMAgent
from constraints import CONSTRAINTS

def main():
    parser = argparse.ArgumentParser(description="Generate a campaign of optimization jobs")
    parser.add_argument("--count", type=int, default=5, help="Number of jobs to generate")
    args = parser.parse_args()

    store = DataStore()
    manager = JobManager(store)
    agent = LLMAgent()

    print(f"Loading history and generating {args.count} jobs...")
    history = store.load_history()

    # Check if agent has model
    if not agent.model:
        print("Error: No LLM available (check GEMINI_API_KEY). Cannot generate campaign.")
        return

    parameter_sets = agent.suggest_campaign(history, CONSTRAINTS, count=args.count)

    if not parameter_sets:
        print("No parameter sets generated by Agent.")
        return

    print(f"Agent proposed {len(parameter_sets)} jobs. Adding to queue...")

    for i, params in enumerate(parameter_sets):
        # Enforce types if needed (simple check)
        if "num_bins" in params:
            params["num_bins"] = int(params["num_bins"])

        job_id = manager.create_job(params)
        print(f"Created Job {i+1}: {job_id}")

    print("Campaign generation complete.")

if __name__ == "__main__":
    main()
